### ISSUE TITLE
Modify naming scheme for `app`s

### ISSUE THREAD

**Issue by monkpit** [linssen/vagrant-puppet-nginx-uwsgi-flask#10]
I'm a developer who is new to deploying using nginx and uwsgi.

I am happy that you have created this resource for me to use to learn, but I am having a little bit of trouble.

The name `app` is used for several things in the various nginx/uwsgi/flask files - app.py, so the module is `app`, app.py defines `app` so the callable is `app`, a location is called `app` in the configs, and maybe more.

For learning purposes, could someone modify these names to be a little more unique? Like renaming app.py to something like flask_source.py, renaming the callable `app` to `flask_callable` or somesuch... changing the manifest variables to `puppet_app_name`, change the uwsgi and nginx names... etc... etc...

I would do it myself - but I'm not even sure if I understand things well enough to do it!

Having them all have distinct names would help me to understand which `app` is coming from where in a given location. With just Python I'm fine, but once Puppet manifests get added in to the mix... I'm confused! 😭

**Comment by linssen** [comment]
:) I feel your pain, @monkpit. My problem is that I've gone full Docker so I'd struggle to set up an env to test this now. Why not have a play and see what works? I'd happily accept a pull request for improvement.

Thanks for the feedback, and sorry for being completely useless.

**Comment by monkpit** [comment]
If I can figure it out, I'll be sure to submit a PR.

Could I ask

**Comment by monkpit** [comment]
>  ... I've gone full docker ...

I've run into this issue with a few different maintainers here on github. I'm curious as to the reasoning - could you give me a brief rundown? What were your reasons to change?

As for the issue itself - if I figure things out, I'll submit a PR!

**Comment by linssen** [comment]
I just find it much more simple to understand, robust, lightweight, and performant. With the new and more tightly integrated OS X and Windows installations, it's getting better, too.
